### ISSUE TITLE
关于CA私钥的疑问

### ISSUE THREAD

**Issue by Xorek** [bcosorg/bcos#33]
https://github.com/bcosorg/bcos/blob/fb0d2a4aab793f2fa417c25f589cee09f4ed6435/libethereum/NodeConnParamsManager.cpp#L648
CA的认证，基于双方交换随机数的CA签名，CA的私钥必须暴露给节点使用。此处是否有可优化的空间？

**Comment by WeWebsterchen** [comment]
因开源版本原因，证书私钥未做保护。建议对存储本地的私钥文件设置密码或把私钥存储在加密机设备中调用加密机接口进行签名操作。
