### ISSUE TITLE
快速安装部署失败

### ISSUE THREAD

**Issue by xiaodeshan** [bcosorg/bcos#45]
错误消息：
E: 无法下载 http://extras.ubuntu.com/ubuntu/dists/xenial/main/binary-amd64/Packages  404  Not Found [IP: 91.189.92.152 80]
E: 无法下载 http://115.156.188.226/extras.ubuntu.com/ubuntu/dists/xenial/main/dep11/icons-64x64.tar  404  Not Found [IP: 91.189.92.152 80]
E: 无法下载 http://ppa.launchpad.net/wengxt/fcitx-nightly/ubuntu/dists/xenial/main/binary-amd64/Packages  404  Not Found
E: 无法下载 http://115.156.188.226/ppa.launchpad.net/wengxt/fcitx-nightly/ubuntu/dists/xenial/main/dep11/icons-64x64.tar  404  Not Found

已经下载了https://github.com/bcosorg/lib中的库，还是会报错
“icons-64x64.tar ”这个包官网上已经失效了
操作系统是Ubuntu16.04

**Comment by burningcpu** [comment]
请问你的操作流程是怎样的？

**Comment by cristicmf** [comment]
@xiaodeshan 建议先看一下这个文档[一键安装部署文档](https://github.com/bcosorg/bcos/wiki/%E4%B8%80%E9%94%AE%E5%BF%AB%E9%80%9F%E5%AE%89%E8%A3%85%E9%83%A8%E7%BD%B2)

**Comment by xiaodeshan** [comment]
已经解决了，原因是系统源配置有点问题，谢谢大家了
