### ISSUE TITLE
有关CA验证部分报错

### ISSUE THREAD

**Issue by liuzuolong** [bcosorg/bcos#56]
根据文档，进行Ca验证的部署
Ca证书是在网站上生成的csr，同时获得了一个private.key，然后后根据文档生成了一个public.key
云服务器，内网的ip
生成文件ca.json如下
{
    "hash":"2ec0d64d4a560f89c088863f9cc848edc45c6fbd0db963e99c6ae93a65159168",
    "pubkey":"MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAjj1DcJt6KK0xuUO043DNFxZqV5rIU8/JzhHBvLCJ569A/jVKooziGFBOJ7eMqwh8FyROLsMCGtM6WN3KwXFKHpIT2+mLECGYtefxXoOKrrXkQJWUsJvW1FOqYkof22wDtzJ9kX5ls5MvKUP9TiV0z3xi4EmCDAZKNY7/ZygYYYzfx6ypyoU79/YJcXqpA2la3d3wwhYiNnix1rCNggsUbL1Qsx5B0D2eOX/4OT9xAsfvySfJC3W04e3mHUmID45/1mW/Qoxs2J2VkQ17ICm89A8QYaUtHHJCeaD4aEIrsN9eP0KHRZZJ+RRLuc0ST5/uTNNRpMDaZiq/Tpsle7LmSwIDAQAB",
    "orgname":"测试机构",
    "notbefore":20170223,
    "notafter":20180223,
    "status":1,
    "whitelist":"192.168.0.5;36.102.228.90",
    "blacklist":""
}
然后按照所说的部署，显示部署成功，但是重启节点之后，一直链接不上
如下
![image](https://user-images.githubusercontent.com/24662306/32826555-d4853a62-ca23-11e7-9e96-cfc72125d87f.png)
日志也不继续出块了，请大家帮忙

**Comment by iamyh** [comment]
方便提供一下文件吗？

1.节点错误日志，可以看看log.conf指明的目录，提供下面的log文件

2.config.json文件和genesis.json文件

另外，有通过文档介绍，开启CA的开关吗？有对系统合约做了什么操作吗？

**Comment by liuzuolong** [comment]
![image](https://user-images.githubusercontent.com/24662306/32830835-709744f6-ca31-11e7-90bc-5fdb02645fe2.png)
![image](https://user-images.githubusercontent.com/24662306/32830861-8590f3de-ca31-11e7-8558-5bb9f5449567.png)
![image](https://user-images.githubusercontent.com/24662306/32830872-90a52eb6-ca31-11e7-9c76-bc494720b2d2.png)
这个其中de的系统合约之前里面是有地址的，然后后续我想初始化的时候删掉的，而且保证都是正确的

之前的三个节点之间是互相链接没有异常的，而且出块也是正常的，但是加上ca验证后，出现了节点之前无法相连接
开启了Ca开关，未对系统合约做其他操作 
但是我感觉一一步骤我做的可能有问题，

“开启开关前，先确保当前所有节点的证书已经上链”

这一步，但是我不知道是不是错的，我是把创世节点的那个ca的mul目录，复制到了其他节点的目录下
/mydata/nodedata-1/data/CA
然后开启开关，然后报错了是不是我这步做的有误
@iamyh

**Comment by liuzuolong** [comment]
我的是单机环境三个节点

**Comment by WeWebsterchen** [comment]
[CA-Use-demo.zip](https://github.com/bcosorg/bcos/files/1474435/CA-Use-demo.zip)
请使用如下步骤生成证书及配置。

**Comment by iamyh** [comment]
CA是需要配置系统合约的，看了一下你的为空？
「初始化删掉」没看懂。
可以参考下@WeWebsterchen 的例子

**Comment by liuzuolong** [comment]
谢谢，我想问一下，Ca证书上链大概是什么意思，是把public.key和private.key放到/mydata/nodedata-1/data/CA/ 目录下吗？是一个节点的两个key都要放到其他节点的当前目录下吗？ @iamyh @WeWebsterchen

**Comment by WeWebsterchen** [comment]
CA节点相连的流程是：未知节点申请连接链上节点需要下发随机数，未知节点需要使用本地的私钥对随机数进行签名。链上节点需要使用未知节点的公钥证书进行签名验证。那这个公钥证书必须在链上合约中（管理员负责上链审核通过的公钥），这就是CA证书上链的意思。

**Comment by liuzuolong** [comment]
@iamyh 
@WeWebsterchen 
您好，按照您的操作，还是无法使用，我的操作就是将private.key和public.key放到CA目录下/mydata/nodedata-X/data/CA下，（将demo生成的key文件改名字了）然后启动三个节点，但是节点都是连接不上
报这个错误请问一下，该如何继续改
admin_peers 返回解析失败！[object Object]
已连接节点数：0
admin_peers 返回解析失败！[object Object]
已连接节点数：0

**Comment by liuzuolong** [comment]
ERROR|2017-11-20 16:54:09|getLeader ret:<1,2>, need viewchange for disconnected
ERROR|2017-11-20 16:54:09|getLeader ret:<1,2>, need viewchange for disconnected
ERROR|2017-11-20 16:54:09|getLeader ret:<1,2>, need viewchange for disconnected

**Comment by WeWebsterchen** [comment]
相关问题在最新版本已做调整，请关注近期最新版本。

**Comment by lmhaoye** [comment]
我发现 registerNode的时候  node*.json 文件中有个CAhash的字段，这里是不是没说明跟证书相关
