### ISSUE TITLE
多节点组网一个节点失败，原网络挂掉

### ISSUE THREAD

**Issue by liuzuolong** [bcosorg/bcos#57]
在做多节点组网的时候
开始是两个节点组网，一个创世节点，链接成功。
然后在增加一个节点
因为我配置错了，导致新的节点的配置信息配置错了，我将其加入到网络后，才发现出现错误，但是原来的的两个正确的节点网络也不重新出块了，那么问题是，然后我想去取消这个节点入网，因为没有新块生成，导致取消入网失败
这个应该怎么去解决

**Comment by iamyh** [comment]
![sample](https://user-images.githubusercontent.com/11833472/32927713-d3a2e4a0-cb13-11e7-8ff8-7ffc881f5852.png)

请开启上帝模式，格式请参考上图。
 **注意**
 1. godMinerStart和godMinerEnd都是16进制
 2. miners的配置请与config.json中保持一致
 3. godMinerEnd必须大于等于godMinerStart
 4. godMinerStart必须等于当前blockchain的块高+1 
          
上面的步骤主要是指定在godMinerStart+1~~godMinerEnd 由miners指定的节点id来出块。在您这种情况下，可以简单设置了某一个可用，无误的节点即可，注意其他的port,desc,ip等需要正确，参考你的config.json对应的配置。

启动说明
          ./eth   --genesis ../genesis.json --config ../config.json --godminer ../godminer.json
在此期间，可以正常出块，你可以添加或者删除有问题的节点。

保证你的所有节点配置已经配置正确，当块高达到godMinerEnd后，再次重启节点。

**Comment by liuzuolong** [comment]
谢谢，已解决并使用

**Comment by shark1212** [comment]
我也出现类似错误，使用上帝模式启动，可是依然去连接有错误的节点
执行babel-node tool.js NodeAction cancelNode 命令依然卡在
Soc File :NodeAction
Func :cancelNode
系统合约地址0xc383063bfa9edb16af8316538f61f649def45875
node.json=nodeYD.json
NodeAction合约地址0xf9234bce6ccba4f7e13a674a3a3ee8028586887d
发送交易成功: 0x998f03ecdbfd1746cdcca6217ce4a4ba4d155de8dc73900a16f27b11c204408a

该怎么处理呢？

**Comment by liuzuolong** [comment]
@shark1212 
首先你要保证的是你上帝模式确实是启动成功的，确实是出块的，我觉得如果你还是卡在那的话，多半是上帝模式启动失败，没有出块

**Comment by shark1212** [comment]
我看了日志，块高确实增加了
我从创世节点来启动处理的，关闭了其他所有节点，不知道这种方式是否正确

**Comment by shark1212** [comment]
@liuzuolong @iamyh 
而且现在发现个问题，我原来的两个正常节点块高不一致了
由于创世节点使用了上帝模式启动，块高增加到了预设的值，而另外一个节点的高度还是原来的值

**Comment by toxotguo** [comment]
@shark1212 
使用同样的上帝模式的配置启动不一致的节点，让节点之间同步到一致的高度。
最后，将所有节点使用正常模式重启。
